using ElementalWords.Interfaces;
using ElementalWords.Models;

namespace ElementalWords.Services;

public class ElementProvider : IElementProvider
{
    private readonly List<IElement> _elements =
   [
       new Element { Symbol = "H", Name = "Hydrogen" },
        new Element { Symbol = "He", Name = "Helium" },
        new Element { Symbol = "Li", Name = "Lithium" },
        new Element { Symbol = "Be", Name = "Beryllium" },
        new Element { Symbol = "B", Name = "Boron" },
        new Element { Symbol = "C", Name = "Carbon" },
        new Element { Symbol = "N", Name = "Nitrogen" },
        new Element { Symbol = "O", Name = "Oxygen" },
        new Element { Symbol = "F", Name = "Fluorine" },
        new Element { Symbol = "Ne", Name = "Neon" },
        new Element { Symbol = "Na", Name = "Sodium" },
        new Element { Symbol = "Mg", Name = "Magnesium" },
        new Element { Symbol = "Al", Name = "Aluminium" },
        new Element { Symbol = "Si", Name = "Silicon" },
        new Element { Symbol = "P", Name = "Phosphorus" },
        new Element { Symbol = "S", Name = "Sulfur" },
        new Element { Symbol = "Cl", Name = "Chlorine" },
        new Element { Symbol = "Ar", Name = "Argon" },
        new Element { Symbol = "K", Name = "Potassium" },
        new Element { Symbol = "Ca", Name = "Calcium" },
        new Element { Symbol = "Sc", Name = "Scandium" },
        new Element { Symbol = "Ti", Name = "Titanium" },
        new Element { Symbol = "V", Name = "Vanadium" },
        new Element { Symbol = "Cr", Name = "Chromium" },
        new Element { Symbol = "Mn", Name = "Manganese" },
        new Element { Symbol = "Fe", Name = "Iron" },
        new Element { Symbol = "Co", Name = "Cobalt" },
        new Element { Symbol = "Ni", Name = "Nickel" },
        new Element { Symbol = "Cu", Name = "Copper" },
        new Element { Symbol = "Zn", Name = "Zinc" },
        new Element { Symbol = "Ga", Name = "Gallium" },
        new Element { Symbol = "Ge", Name = "Germanium" },
        new Element { Symbol = "As", Name = "Arsenic" },
        new Element { Symbol = "Se", Name = "Selenium" },
        new Element { Symbol = "Br", Name = "Bromine" },
        new Element { Symbol = "Kr", Name = "Krypton" },
        new Element { Symbol = "Rb", Name = "Rubidium" },
        new Element { Symbol = "Sr", Name = "Strontium" },
        new Element { Symbol = "Y", Name = "Yttrium" },
        new Element { Symbol = "Zr", Name = "Zirconium" },
        new Element { Symbol = "Nb", Name = "Niobium" },
        new Element { Symbol = "Mo", Name = "Molybdenum" },
        new Element { Symbol = "Tc", Name = "Technetium" },
        new Element { Symbol = "Ru", Name = "Ruthenium" },
        new Element { Symbol = "Rh", Name = "Rhodium" },
        new Element { Symbol = "Pd", Name = "Palladium" },
        new Element { Symbol = "Ag", Name = "Silver" },
        new Element { Symbol = "Cd", Name = "Cadmium" },
        new Element { Symbol = "In", Name = "Indium" },
        new Element { Symbol = "Sn", Name = "Tin" },
        new Element { Symbol = "Sb", Name = "Antimony" },
        new Element { Symbol = "Te", Name = "Tellurium" },
        new Element { Symbol = "I", Name = "Iodine" },
        new Element { Symbol = "Xe", Name = "Xenon" },
        new Element { Symbol = "Cs", Name = "Cesium" },
        new Element { Symbol = "Ba", Name = "Barium" },
        new Element { Symbol = "La", Name = "Lanthanum" },
        new Element { Symbol = "Ce", Name = "Cerium" },
        new Element { Symbol = "Pr", Name = "Praseodymium" },
        new Element { Symbol = "Nd", Name = "Neodymium" },
        new Element { Symbol = "Pm", Name = "Promethium" },
        new Element { Symbol = "Sm", Name = "Samarium" },
        new Element { Symbol = "Eu", Name = "Europium" },
        new Element { Symbol = "Gd", Name = "Gadolinium" },
        new Element { Symbol = "Tb", Name = "Terbium" },
        new Element { Symbol = "Dy", Name = "Dysprosium" },
        new Element { Symbol = "Ho", Name = "Holmium" },
        new Element { Symbol = "Er", Name = "Erbium" },
        new Element { Symbol = "Tm", Name = "Thulium" },
        new Element { Symbol = "Yb", Name = "Ytterbium" },
        new Element { Symbol = "Lu", Name = "Lutetium" },
        new Element { Symbol = "Hf", Name = "Hafnium" },
        new Element { Symbol = "Ta", Name = "Tantalum" },
        new Element { Symbol = "W", Name = "Tungsten" },
        new Element { Symbol = "Re", Name = "Rhenium" },
        new Element { Symbol = "Os", Name = "Osmium" },
        new Element { Symbol = "Ir", Name = "Iridium" },
        new Element { Symbol = "Pt", Name = "Platinum" },
        new Element { Symbol = "Au", Name = "Gold" },
        new Element { Symbol = "Hg", Name = "Mercury" },
        new Element { Symbol = "Tl", Name = "Thallium" },
        new Element { Symbol = "Pb", Name = "Lead" },
        new Element { Symbol = "Bi", Name = "Bismuth" },
        new Element { Symbol = "Po", Name = "Polonium" },
        new Element { Symbol = "At", Name = "Astatine" },
        new Element { Symbol = "Rn", Name = "Radon" },
        new Element { Symbol = "Fr", Name = "Francium" },
        new Element { Symbol = "Ra", Name = "Radium" },
        new Element { Symbol = "Ac", Name = "Actinium" },
        new Element { Symbol = "Th", Name = "Thorium" },
        new Element { Symbol = "Pa", Name = "Protactinium" },
        new Element { Symbol = "U", Name = "Uranium" },
        new Element { Symbol = "Np", Name = "Neptunium" },
        new Element { Symbol = "Pu", Name = "Plutonium" },
        new Element { Symbol = "Am", Name = "Americium" },
        new Element { Symbol = "Cm", Name = "Curium" },
        new Element { Symbol = "Bk", Name = "Berkelium" },
        new Element { Symbol = "Cf", Name = "Californium" },
        new Element { Symbol = "Es", Name = "Einsteinium" },
        new Element { Symbol = "Fm", Name = "Fermium" },
        new Element { Symbol = "Md", Name = "Mendelevium" },
        new Element { Symbol = "No", Name = "Nobelium" },
        new Element { Symbol = "Lr", Name = "Lawrencium" },
        new Element { Symbol = "Rf", Name = "Rutherfordium" },
        new Element { Symbol = "Db", Name = "Dubnium" },
        new Element { Symbol = "Sg", Name = "Seaborgium" },
        new Element { Symbol = "Bh", Name = "Bohrium" },
        new Element { Symbol = "Hs", Name = "Hassium" },
        new Element { Symbol = "Cn", Name = "Copernicium" },
        new Element { Symbol = "Nh", Name = "Nihonium" },
        new Element { Symbol = "Fl", Name = "Flerovium" },
        new Element { Symbol = "Mc", Name = "Moscovium" },
        new Element { Symbol = "Lv", Name = "Livermorium" },
        new Element { Symbol = "Ts", Name = "Tennessine" },
        new Element { Symbol = "Og", Name = "Oganesson" }
   ];

    public List<IElement> GetElements()
    {
        return _elements;
    }
}
